### ISSUE TITLE
Logo- und Attachments des Events im schedule.xml

### ISSUE THREAD

**Issue by MaZderMind** [cccc/media-backend#9]
Derzeit sind weder das Talk-Logo- noch die URLs zu den vom Referenten hochgeladenen Attachments im schedule.xml enthalten. Das ist IMO ein Bug und sollte gefixt werden.

Dadurch könnten diese Files auch von der Media-API geladen und auf media.ccc.de angeboten werden.

**Comment by saerdnaer** [comment]
@MaZderMind Warum ist das ein Issue des media-backend's und nicht vom Frab?

**Comment by MaZderMind** [comment]
war ein versehen. Moved -> https://github.com/frab/frab/issues/157
